### ISSUE TITLE
[feature] !challenge 커맨드 생성

### ISSUE THREAD

**Issue by ativ-sodo** [AtivSolana/nois-sol-bot#20]
## Description
shill 2 earn 기능 검증을 위하여 discord bot 기반 MVP를 개발하고자 함. !challenge 는 last.fm에서 챌린지로 등록 된 노래의 play count를 가져오는 기본 커맨드이다.

**[challenge 커맨드 플로우]**
1. discord에서  유저가 !challenge를 타이핑함.
2. 유저가 connect_counter 커맨드를 완료하지 않은 경우에는 connect_counter 커맨드를 완료해달라는 이미지를 전달한다.
3. updateChallengePlayCount mutaion을 호출한다.
4. mutation의 return 값을 바탕으로 유저에게 play count를 reply 한다.

## Data
- 

## Acceptance Criteria
- [x] connect 커맨드를 완료하지 않은 유저가 커맨드를 입력한 경우 connect 커맨드를 완료해달라는 텍스트를 전달한다.
- [x] last.fm 연결이 완료된 유저의 경우 updateChallengePlayCount mutation을 호출하여 곡 플레이 횟수를 업데이트 한.
- [x] 곡 플레이 횟수를 업데이트 한 이후 유저에게 현재 시점의 곡 플레이 횟수를 전달한다.

**Comment by ativ-sodo** [comment]
@ativ-sonic 검토 부탁드립니다!

**Comment by ativ-sonic** [comment]
@ativ-sodo 확인했습니다!
