### ISSUE TITLE
[feature] Discord 라이브러리 변경

### ISSUE THREAD

**Issue by ativ-sonic** [AtivSolana/nois-sol-bot#21]
## Description
Discord 공식 파이썬 라이브러리에서는 slash command 이외의 command에 대해 ephemeral message(자신에게만 보이는 메시지)를 지원하지 않기 때문에 이를 해결하기 위해 라이브러리를 변경하고자 함.

## Data
- 기본적으로는 비워놓되, API 연결이 필요할 경우 소도가 적음.

## Acceptance Criteria
- [ ] 새로운 라이브러리 적용
- [ ] Ephemeral message 작동 확인
- [ ] 기존 기능 작동 확인

**Comment by ativ-sodo** [comment]
기존 라이브러리를 활용하여 우회 할 수 있는 방법으로 개발 가능함을 확인하였음.
우회 방법으로 개발 하는 것은 #23 에서 진행하고 있음. 
해당 이슈는 close 합니다!
