### ISSUE TITLE
[feature] 디스코드 submit-wallet 채널을 통해 지갑 주소 수집

### ISSUE THREAD

**Issue by ativ-sonic** [AtivSolana/nois-sol-bot#47]
## Description
노이즈리스트, 화이트리스트, 이벤트 위너 등의 지갑 주소 수집을 위해 디스코드에 submit-wallet 채널을 만들고 interaction button을 통해 직접 입력하는 방식을 사용하고자 함. 추가로 check wallet 버튼을 통해 본인이 입력한 지갑 주소를 확인할 수 있음.

## Data
- registerWallet mutation 활용
```
mutation {
  registerWallet(discordId:"", walletAddress: "") {
		success
  }
}
```
-  user query 활용 (user의 sollana wallet 가져오기)
```
query {
  user(discordId:"") {
    walletAddress
  }
}
```

## Technical Details
- [x] 디스코드로부터 받은 지갑 주소를 정상적으로 NOIS-BE에 업데이트
- [x] 유저가 check wallet을 했을 때 입력했던 지갑 주소를 정상적으로 reply

## Acceptance Criteria
- [x] 디스코드 submit-wallet 채널의 버튼을 눌렀을 때, 지갑 주소 입력 폼 모달 팝업
- [x] 지갑주소가 Solana 블록체인에서 유효하지 않을 경우 유효하지 않다는 히든 메시지 reply
- [x] 지갑주소가 Solana 블록체인에서 유효할 경우 정상적으로 제출되었다는 히든 메시지 reply
- [x] Check wallet을 했을 때, 지갑 주소 제출이 되지 않았을 경우 지갑 주소 제출을 먼저 하라는 히든 메시지 reply
- [x] Check wallet을 했을 때, 지갑 주소 제출이 된 경우 올바른 지갑 주소 히든 메시지 reply

**Comment by ativ-sodo** [comment]
@ativ-sonic API 업데이트 하였습니다!
