### ISSUE TITLE
[feature] !status 커맨드를 유저가 입력할 경우 보유하고 있는 상자 개수와 번 USDC를 보여줌

### ISSUE THREAD

**Issue by ativ-sonic** [AtivSolana/nois-sol-bot#49]
## Description
유저의 현재 보유 상자 개수와 획득한 USDC를 보여주기 위한 !status 커맨드 개발

## Data
-  user query 활용 (아직 클레임하지 않은 usdc, 오픈하지 않은  box 개수 가져오)
```
query {
  user(discordId:"") {
    walletAddress
    amountOfUsdc
    numberOfBoxes
  }
}
```

## Technical Details
- [x] NOIS-BE의 NoisUser에 discord_id를 통해 USDC 개수 정상적으로 불러오기
- [x] NOIS-BE의 NoisUser에 discord_id를 통해 Box 개수 정상적으로 불러오기

## Acceptance Criteria
- [x] 유저가 !status를 입력했을 때, Box, USDC 개수가 정확하게 Reply
- [x] 유저가 db에 없을 시, !connect를 통해 연결을 먼저 하라는 메시지 Reply

**Comment by ativ-sodo** [comment]
@ativ-sonic api 업데이트 되었습니다
