### ISSUE TITLE
[feature] !challenge를 했을 때 Justice와 Locked up 스포티파이 플레이 카운트가 나오도록 수정 

### ISSUE THREAD

**Issue by ativ-sodo** [AtivSolana/nois-sol-bot#50]
## Description
Locked Up 출시 했을 때 Justice와 Locked up 스포티파이 플레이 카운트 달성 이벤트를 진행하고자 함. 각 곡의 플레이 횟수를 유저에게 알려줄 수 있는 채널이 필요하여 !challenge 커맨드를 유저가 입력 했을 때 Justice와 Locked up 스포티파이 플레이 카운트가 나오도록 수정하고자 함.

## Data
- 

## Technical Details
- [x] UTC 기준 8 pm 이후에 처음으로 !challenge 커맨드가 입력되면 json 파일에 입력된 시간과 스포티파이 플레이카운트를 업데이트한.
- [x] 추후 NOIS-BE의 그룹챌린지 DB 모델을 가져오는 방식으로 구현이 될 테니 연동이 쉽도록 코드 리팩토링 진행

## Acceptance Criteria
- [x] !challenge 커맨드를 유저가 입력 했을 때 Justice와 Locked up 스포티파이 플레이 카운트가 나옴.

**Comment by ativ-sodo** [comment]
@ativ-sonic 오늘 이벤트 오픈 전까지 임시로 진행할 태스크입니다. 확인 부탁드려요!

**Comment by ativ-sonic** [comment]
@ativ-sodo 확인했습니다.
